spring:
  profiles:
  active: abc,bcd
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mydb?serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
server:
  port: 80

